// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Token struct {
	ID        string
	Token     string
	Valid     int64
	CreatedAt string
	RevokedAt sql.NullString
	Userid    string
}

type User struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	Name         string
	Email        string
	Passwordhash string
}
