// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (id, token, valid, created_at, revoked_at, userid)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID        string
	Token     string
	Valid     int64
	CreatedAt string
	RevokedAt sql.NullString
	Userid    string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.Token,
		arg.Valid,
		arg.CreatedAt,
		arg.RevokedAt,
		arg.Userid,
	)
	return err
}

const getTokenByToken = `-- name: GetTokenByToken :one
SELECT id, token, valid, created_at, revoked_at, userid FROM tokens WHERE token = ?
`

func (q *Queries) GetTokenByToken(ctx context.Context, token string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByToken, token)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Valid,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Userid,
	)
	return i, err
}
