name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_TURSO: ${{ secrets.DB_CONNECTION_TURSO }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
      
      - name: Build App
        working-directory: ./api
        run: ./../scripts/buildprod.sh
      
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
    
      - name: Submit Build
        working-directory: ./api
        run: gcloud builds submit --tag europe-west2-docker.pkg.dev/webnovelapi/webnovelapi-ar-repo/webnovelapi:latest .
      
      - name: install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
  
      - name: Migrate DB
        working-directory: ./api
        run: ./../scripts/migrateup.sh
      
      - name: Deploy to Cloud Run
        run: gcloud run deploy webnovelapi --image europe-west2-docker.pkg.dev/webnovelapi/webnovelapi-ar-repo/webnovelapi:latest --region europe-west2 --allow-unauthenticated --project webnovelapi --max-instances=4